name: Build and test
on: push
jobs:
  node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: oven-sh/setup-bun@v1
    - name: Node.js v20
      uses: actions/setup-node@v1
      with:
        node-version: 20
    - run: bun install --frozen-lockfile
    - run: npm run build
    - run: npm run test
  bun:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bun v1
      uses: oven-sh/setup-bun@v1
      with:
        node-version: 1
    - run: bun install --frozen-lockfile
    - run: bun run build
    - run: bun run test
