name: Build and test
on: workflow_call
jobs:
  node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
    - name: Node.js v23
      uses: actions/setup-node@v3
      with:
        node-version: 23
    - run: bun install --frozen-lockfile
    - run: npm run build
    - run: npm run test
  bun:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Bun v1
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.2
    - run: bun install --frozen-lockfile
    - run: bun run build
    - run: bun run --bun test
