name: Deploy
on: workflow_call
jobs:
  deploy:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bun v1
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun build site/index.html --outdir=dist/site
      - run: cp -r assets dist/site
      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: dist/site/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
